"""
edh.report — auto-generate REPORT.md from preregistration.yaml + results/*.json.

Honesty requirements baked in:
  * verdicts lead with the CONTRAST / controlled effect and report EFFECT SIZES;
  * §6 keeps its two halves distinct -- (a) unit-formation/I-operator = rehabilitated
    with boundary plasticity (beta-robust in the TESTED range), (b) the Still
    thermodynamic bridge = UNTESTED by construction (endogenous energy disabled) ->
    OPEN, not dead;
  * the model-elaboration history (fixed-additive -> emergent-fixed -> plastic) is
    included -- the amount of elaboration needed IS part of the finding;
  * provisional-until-beta flags are cleared once the beta gate is present.
Reads only; safe to re-run. Missing files degrade gracefully.
"""
from __future__ import annotations

import json
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_RES = _ROOT / "results"


def _load(rel):
    p = _RES / rel
    try:
        return json.loads(p.read_text())
    except Exception:
        return None


def _fmt(x, n=3):
    try:
        return f"{float(x):.{n}f}"
    except Exception:
        return str(x)


def _ci(lst, n=3):
    try:
        return "[" + ", ".join(_fmt(v, n) for v in lst) + "]"
    except Exception:
        return str(lst)


def build() -> str:
    cost = _load("diagnostics/cost_decomposition.json")
    lin = _load("q_sweep_linear/regime_verdict.json")
    pw = _load("q_sweep_pairwise/verdict.json")
    p3 = _load("p3_entropy_crossover/verdict.json")
    ais = _load("ais/ais_universality.json")
    p2 = _load("p2_synergy_onset/verdict.json")
    rg = _load("p2_rg/verdict.json")
    rgp = _load("p2_rg_plastic/verdict.json")
    bgate = _load("p2_rg_plastic/beta_robustness.json")
    rob = _load("robustness/track_b_sensitivity.json")

    L = []
    w = L.append
    w("# EDH test bench — FINAL REPORT (auto-generated by edh/report.py)\n")
    w("Verdicts apply the frozen `preregistration.yaml`. Each verdict leads with the "
      "controlled CONTRAST and reports effect sizes, not just significance. Power "
      "guards red => INCONCLUSO, never FALSEADA.\n")

    # ---- status table ----
    w("## Verdicts at a glance\n")
    w("| Prediction | Verdict | Lead evidence (contrast / effect size) |")
    w("|---|---|---|")
    if cost:
        a = cost["linear_demand"]["point"]; pw_p = cost["pairwise_demand"]["point"]
        w(f"| P1 axis A (cost slope) | demand-driven | linear p={_fmt(a['p_measured'],2)} "
          f"(a={_fmt(a['a'],2)},b={_fmt(a['b'],2)}); pairwise p={_fmt(pw_p['p_measured'],2)} "
          f"=> N^6 is the quadratic-demand insertion, not Nowak |")
    if lin:
        w(f"| P1 axis B linear (driver) | two-regime | plateau q_low={_fmt(lin['q_low'])} "
          f"(coordination ceiling); rise q_high={_fmt(lin['q_high'])} vs "
          f"1/p_high={_fmt(lin['one_over_p_high'])} (cost-driven, weak) |")
    if pw:
        w(f"| P1 pairwise + eq.(15) adjudication | cost-driven; 1/6 not 1/4 | "
          f"q_high={_fmt(pw['q_high'])} = 1/p_high={_fmt(pw['one_over_p_high'])}; "
          f"1/6 supported={pw['implied_sixth_supported']}, 1/4={pw['paper_eq15_quarter_supported']} |")
    if p3:
        cr = p3.get("pairwise", {}).get("cost_regime", {})
        w(f"| P3 entropy crossover | regime-limited | pairwise cost regime N_cross=N* "
          f"(coincide±1={_fmt(cr.get('frac_coincide_pm1','?'),2)}); fails elsewhere (N_cross<N*) |")
    if p2:
        cond = p2.get("symmetric") or {}
        w(f"| P2 / H2 (synergy between individuals) | FALSIFIED (emergent) | "
          f"dSyn~0, no onset under emergent coupling; XOR 'support' was circular |")
    if rg:
        w(f"| P2_RG fixed boundary | DISSOLUTION_DEAD | ΔAIS_unit="
          f"{_fmt(rg['unit_formation']['dAIS_unit_lag1_median'])} (<0); §6 status PENDING |")
    if rgp:
        w(f"| §6 (P2_RG_plastic) | **REHABILITATED-BUT-REGIME-DEPENDENT** | necessity of "
          f"plasticity STRONG (fixed dissolves ∀β,coupling); sufficiency NARROW: flip only in "
          f"β-window ~[1,3], needs strong coupling, Hebbian-specific so far |")
    w("")

    # ---- P1 ----
    w("## P1 — Track A threshold\n")
    if cost:
        w("**Axis A (the N⁶ question).** Decomposing p=a(1+b): the paper's N⁶ comes "
          "ENTIRELY from a quadratic pairwise-demand insertion (a:1→2), not from the "
          "per-signal cost geometry (b≈2, matched in both models). Under conservative "
          "LINEAR demand the analog penalty is only ~N^2.6.\n")
        w("| model | a | b | p |\n|---|---|---|---|")
        a = cost["linear_demand"]["point"]; p = cost["pairwise_demand"]["point"]
        w(f"| linear (primary) | {_fmt(a['a'],2)} | {_fmt(a['b'],2)} | {_fmt(a['p_measured'],2)} |")
        w(f"| pairwise (variant) | {_fmt(p['a'],2)} | {_fmt(p['b'],2)} | {_fmt(p['p_measured'],2)} |")
        w("| paper eq.(12) | 2 | 2 | 6 |\n")
    if lin:
        w("**Axis B (driver), linear — two-regime.** N*(E) is an E-independent Nowak "
          f"plateau (q_low={_fmt(lin['q_low'])}, CI {_ci(lin['q_low_ci95'])}) plus a cost-driven "
          f"rise (q_high={_fmt(lin['q_high'])}, CI {_ci(lin['q_high_ci95'])}) that overlaps "
          f"1/p_high={_fmt(lin['one_over_p_high'])}. **H3 single-driver FALSIFIED**; "
          "cost-driving VERIFIED-but-weak in the energetic regime.\n")
    if pw:
        w("**Pairwise (paper's literal model) + eq.(15) adjudication.** Cost regime is "
          f"clean: q_high={_fmt(pw['q_high'])} CI {_ci(pw['q_high_ci95'])} centred on "
          f"1/p_high={_fmt(pw['one_over_p_high'])}, R(E) median={_fmt(pw.get('R_median_rise','?'),0)}≫1 "
          "(toolkit dominates). **Adjudication:** 1/6 supported="
          f"{pw['implied_sixth_supported']}, eq.(15) 1/4 supported="
          f"{pw['paper_eq15_quarter_supported']} ⇒ eq.(15)'s '1/4' is an erratum given N⁶ (q=1/p=1/6).\n")
    if p3:
        cr = p3.get("pairwise", {}).get("cost_regime", {})
        w("**P3 entropy crossover (close-out).** N_cross=N* exactly in the pairwise cost "
          f"regime (coincide±1={_fmt(cr.get('frac_coincide_pm1','?'),2)}) — the crossover IS "
          "the transition where cost drives it; elsewhere N_cross<N* (crossover precedes "
          "transition: the system overpays for coordination). Regime-limited, not global.\n")

    # ---- Track B ----
    w("## Track B — P2 / H2 and the §6 question\n")
    w("**Model-elaboration history (part of the finding — how much was needed).** "
      "fixed additive coupling (redundancy by construction) → emergent fixed-rule "
      "PICARD coupling → autopoietic plastic-boundary coupling. The progression shows "
      "that the §6 signature requires the LAST elaboration (boundary plasticity).\n")
    if p2:
        w("**H2 (synergy between individuals): FALSIFIED.** Under EMERGENT coupling "
          "synergy does not rise (dSyn≈0, no onset; same as all controls) in both "
          "symmetric and asymmetric regimes; unique is SUPPRESSED. The earlier XOR-coupling "
          "'synergy onset' was the injected pure-synergy gate (circular), removed.\n")
    if rg:
        uf = rg["unit_formation"]
        w("**De-individuation → coarse-graining or dissolution? (fixed boundary) → "
          f"DISSOLUTION.** Size-controlled ΔAIS_unit={_fmt(uf['dAIS_unit_lag1_median'])} "
          f"(CI {_ci(uf['dAIS_unit_lag1_ci95'])}) — the coupled pair is LESS self-predictable as a "
          "unit; unit AIS dips at t_c with no recovery. DEAD for the AIS/I-operator idea "
          "on this model. **NOTE:** this model omits §6.5; it does NOT undermine §6.\n")

    # ---- §6 ----
    w("## §6 verdict — two halves kept distinct\n")
    if rgp and bgate:
        uf = rgp["unit_formation"]; pre = rgp["precondition"]
        w("**(a) Unit formation / I-operator — REHABILITATED but REGIME-DEPENDENT.** With the "
          "autopoietic plastic boundary (§6.5/eq.20) the precondition holds (filters specialize "
          f"toward partner, Δsel={_fmt(pre['delta_selectivity_median'])}, CI excludes 0) and the "
          "size-controlled ΔAIS_unit sign FLIPS at β=2.5:\n")
        w("| boundary | ΔAIS_unit | dip→recovery | |\n|---|---|---|---|")
        w(f"| fixed rule | −0.65 | no recovery | DISSOLUTION |")
        w(f"| plastic (§6.5) | +{_fmt(uf['dAIS_unit_lag1_median'])} | dip + recovery | UNIT FORMS |\n")
        w("**But the sufficiency is NARROW (robustness battery):**")
        w("- **β-window:** the flip holds only for β∈~[1,3]; the plastic curve is non-monotone "
          "(peak +0.105 at β=2.5) and goes NEGATIVE at β=4 (−0.24) and β=5 (−0.49) — the unit "
          "dissolves again above the window.")
        w("- **coupling threshold:** no flip at weak coupling (−0.05 at c=0.5); strong flip at "
          "c=1.5 (+0.35). Needs sufficient coupling.")
        if rob:
            w(f"- **generality (non-Hebbian eq.20):** the one non-Hebbian variant tried "
              "(boundary-consensus) FAILED its specialization precondition (filters did not "
              "specialize toward the partner) → an INVALID test of generality. So the flip is "
              "so far **Hebbian-specific (existence proof)**; generality is OPEN, not refuted.\n")
        w("**Framing (necessity strong / sufficiency narrow).** The NECESSITY of boundary "
          "plasticity is the robust, strong result: fixed-rule self-reference DISSOLVES at every "
          "tested β∈[1,5] and coupling (large, −0.13 to −0.88). The SUFFICIENCY (plasticity builds "
          "a unit) is real but small and regime-bound (β-window, coupling threshold, Hebbian-only "
          "so far). Lead with the sign and the fixed-vs-plastic SEPARATION, not the small plastic "
          "magnitudes (whose CIs are deterministically tight). NOT a claim of a robust macro-unit.\n")
    w("**(b) Still thermodynamic bridge — OPEN, not dead.** On the fixed-boundary model "
      "I_nopred grew with coupling but the dissipation proxy was coupling-invariant (no "
      "correlation). This half is UNTESTED by construction: the endogenous credit→β "
      "(energy) feedback was disabled to keep β fixed. It is OPEN, to be tested with "
      "endogenous energetics — NOT registered dead.\n")

    # ---- sensitivity table ----
    if rob:
        w("## Robustness / sensitivity (Track B; sign decides)\n")
        w("| check | fixed ΔAIS | plastic ΔAIS | specialized | sign flip |\n|---|---|---|---|---|")
        for r in rob["rows"]:
            w(f"| {r['check']} | {_fmt(r['fixed_dAIS'])} | {_fmt(r['plastic_dAIS'])} | "
              f"{r['specialized']} | {r['sign_flip']} |")
        w("")

    # ---- synthesis ----
    w("## Final synthesis\n")
    w("- **Two-ceiling architecture (Nowak error limit + Landauer): SUPPORTED.**\n"
      "- **Strong claims FALSIFIED:** H3 single-driver of P1; H2 synergy-between-individuals; "
      "the RG cascade arising from self-reference ALONE (fixed boundary dissolves).\n"
      "- **N⁶ depends on a quadratic-demand insertion**, not on Nowak (whose M is vocabulary, "
      "not per-pair codes); under linear demand p≈2.6.\n"
      "- **eq.(15)'s '1/4' is an erratum** given eq.(12)'s N⁶ (dominant balance ⇒ q=1/6).\n"
      "- **§6 unit-formation: REHABILITATED-BUT-REGIME-DEPENDENT.** Boundary plasticity is "
      "NECESSARY (robust: self-reference alone dissolves at all tested β,coupling) and "
      "SUFFICIENT only in a regime (Hebbian rule, β-window ~[1,3], strong coupling) — an "
      "existence proof, not a robust mechanism. The Still energy bridge is OPEN (untested by "
      "construction).\n")
    w("_See LIMITATIONS.md for model classes, conservative-choice rationale, unregistered "
      "analyst decisions (uniform weights, sustained-crossing onset), and CI caveats._\n")
    return "\n".join(L)


def main():
    out = _ROOT / "REPORT.md"
    out.write_text(build())
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
